EventFinder_GC/Models/CustomerEvent.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace EventFinder_GC.Models
{
    public class CustomerEvent
    {
        
        
    
        [Key, Column(Order = 1), ForeignKey("Event")]
        
        public int EventId { get; set; }
        public Event Event { get; set; }
        
        [Key, Column(Order = 2), ForeignKey("Customer")]
        
        public int CustomerId { get; set; }
        public Customer Customer { get; set; }
    }
}

EventFinder_GC/Controllers/CustomerEventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EventFinder_GC.Models;

namespace EventFinder_GC.Controllers
{
    public class CustomerEventsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: CustomerEvents
        public ActionResult Index()
        {
            var customerEvents = db.CustomerEvents.Include(c => c.Customer).Include(c => c.Event);
            
            return View("List",customerEvents.ToList());
        }

        // GET: CustomerEvents/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomerEvent customerEvent = db.CustomerEvents.Find(id);
            if (customerEvent == null)
            {
                return HttpNotFound();
            }
            return View(customerEvent);
        }

        // GET: CustomerEvents/Create
        public ActionResult Create()
        {
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "FirstName");
            ViewBag.EventId = new SelectList(db.Events, "EventId", "EventName");
            return View();
        }

        // POST: CustomerEvents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EventId,CustomerId")] CustomerEvent customerEvent)
        {
            if (ModelState.IsValid)
            {
                db.CustomerEvents.Add(customerEvent);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "FirstName", customerEvent.CustomerId);
            ViewBag.EventId = new SelectList(db.Events, "EventId", "EventName", customerEvent.EventId);
            return View(customerEvent);
        }

        public ActionResult FilterByCat(string subCategory)
        {
            var events = db.Events.Include(e => e.Address).Include(e => e.Host);
            var newEvents = events.Where(e => e.SubCategory == subCategory);
            return View("Index", newEvents);
        }

        // GET: CustomerEvents/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomerEvent customerEvent = db.CustomerEvents.Find(id);
            if (customerEvent == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "FirstName", customerEvent.CustomerId);
            ViewBag.EventId = new SelectList(db.Events, "EventId", "EventName", customerEvent.EventId);
            return View(customerEvent);
        }

        // POST: CustomerEvents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EventId,CustomerId")] CustomerEvent customerEvent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customerEvent).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "FirstName", customerEvent.CustomerId);
            ViewBag.EventId = new SelectList(db.Events, "EventId", "EventName", customerEvent.EventId);
            return View(customerEvent);
        }

        // GET: CustomerEvents/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomerEvent customerEvent = db.CustomerEvents.Find(id);
            if (customerEvent == null)
            {
                return HttpNotFound();
            }
            return View(customerEvent);
        }

        // POST: CustomerEvents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CustomerEvent customerEvent = db.CustomerEvents.Find(id);
            db.CustomerEvents.Remove(customerEvent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EventFinder_GC/Views/CustomerEvents/Create.cshtml
 {
 @model EventFinder_GC.Models.CustomerEvent

    @{
        ViewBag.Title = "Create";
    }

    <h2>Create</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>CustomerEvent</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.EventId, "EventId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("EventId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.EventId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CustomerId, "CustomerId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CustomerId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

EventFinder_GC/Views/CustomerEvents/Delete.cshtml
@model EventFinder_GC.Models.CustomerEvent

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CustomerEvent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Customer.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Event.EventName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Event.EventName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EventFinder_GC/Views/CustomerEvents/Details.cshtml
@model EventFinder_GC.Models.CustomerEvent

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CustomerEvent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Customer.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Event.EventName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Event.EventName)
        </dd>

    </dl>
</div>
<input type="button" value="Create" onclick="location.href='@Url.Action("Create", "CustomerEvents")'" />
<p>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.CustomerId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EventFinder_GC/Views/CustomerEvents/Edit.cshtml
@model EventFinder_GC.Models.CustomerEvent

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CustomerEvent</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EventId)

        @Html.HiddenFor(model => model.CustomerId)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EventFinder_GC/Views/CustomerEvents/Index.cshtml
@model IEnumerable<EventFinder_GC.Models.CustomerEvent>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Customer.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Event.EventName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Customer.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Event.EventName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

EventFinder_GC/Views/CustomerEvents/List.cshtml
@model IEnumerable<EventFinder_GC.Models.CustomerEvent>

@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Customer.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Event.EventName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Customer.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Event.EventName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>